### PR TITLE
Feature/ml 566 aakd on the sdk repo when i do a release

### PR DESCRIPTION
**Pull request by PierreLeveau**

### CODE REVIEW

**Comment by theodu** [comment]
@PierreLeveau I advanced on it today, the deployment of the doc now works from the publish script!

**Review by theodu — APPROVED** [review]

**Comment by theodu** [comment]
@pierre I also added the entrypoint.sh
-> ./entrypoint.sh bump:minor
-> ./entrypoint.sh bump:patch

it:
1- checkouts to `master` and pulls
2- creates or overrides a `branch release/bump-version` from up-to-date `master`
3- makes the bump on this branch
4- pushes it and creates a PR with some pre-assigned reviewers

As a tag can be created from another commit than this one (we can for example continue to develop after the bump and make the release from a commit after), I didn't go further into the programatic release creation. I think that it can be added later if needed.

**Comment by PierreLeveau** [comment]
> As a tag can be created from another commit than this one (we can for example continue to develop after the bump and make the release from a commit after), I didn't go further into the programatic release creation. I think that it can be added later if needed.

Excellent! I think we should keep the tag creation as part of the actual release. Which we can keep doing manually or pre-fill with a script.

**Review by PierreLeveau — COMMENTED** [review]
I approve (I can't approve formally as I am the PR author)

**Pull request merged**
