### PR TITLE
fix: change css font size on the SDK doc website

### PR DESCRIPTION
**Pull request by theodu**

### CODE REVIEW

**Comment by Jonas1312** [comment]
looks better IMO.

I wonder if we shouldn't also  reduce the TOCs font size (currently 16.8px) ?  Maybe 16px or 15px?

It's defined in `.md-nav`

**Comment by theodu** [comment]
Yes it looks better now!
When I inspect, I see the nav font-size at `14px`, and it seems good. Strange that you see it at `16.8px`, can you send a screenshot ?

**Comment by theodu** [comment]
oh, I don't have this fonts tab, it is useful!
Personally, I find the size of the nav good that way and I wouldn't change it. What do you think @PierreLeveau  ?

**Review by PierreLeveau — APPROVED** [review]

**Comment by PierreLeveau** [comment]
LGTM

**Pull request merged**
